src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 */
class News
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=128, unique=true)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="smallint", options={"default": 0})
     */
    private $view = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="news")
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $metaDescription;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $instagramToken;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $heading;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $parentPage = "Články";

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true, options={"default": "CURRENT_TIMESTAMP"})
     */
    private $addedAt;

    /**
     * @ORM\ManyToMany(targetEntity=NewsCategories::class, inversedBy="news")
     */
    private $newsCategories;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $notation;

    public function __construct()
    {
        $this->newsCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->metaDescription;
    }

    public function setMetaDescription(?string $metaDescription): self
    {
        $this->metaDescription = $metaDescription;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getInstagramToken(): ?string
    {
        return $this->instagramToken;
    }

    public function setInstagramToken(?string $instagramToken): self
    {
        $this->instagramToken = $instagramToken;

        return $this;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): self
    {
        $this->heading = $heading;

        return $this;
    }

    public function getParentPage(): ?string
    {
        return $this->parentPage;
    }

    public function setParentPage(?string $parentPage): self
    {
        $this->parentPage = $parentPage;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt(\DateTime $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt(\DateTime $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function getView(): ?int
    {
        return $this->view;
    }

    public function setView($view): self
    {
        $this->view = $view;

        return $this;
    }

    public function hide(): self
    {
        $this->view = 0;

        return $this;
    }

    public function show(): self
    {
        $this->view = 1;

        return $this;
    }

    public function getImgName(): ?string
    {
        return $this->img_name;
    }

    public function setImgName(string $img_name): self
    {
        $this->img_name = $img_name;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(?string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getImgPath($index = null): ?string
    {
        if (null !== $index && '' !== $index) {
            if (file_exists('uploads/news/'.$index)) {
                return 'uploads/news/'.$index;
            } else if (file_exists('build/images/news/'.$index)) {
                return 'build/images/news/'.$index;
            }
        }

        return 'build/images/utilities/pripravujeme-dark.png';
    }

    public function getAddedAt(): ?\DateTimeImmutable
    {
        return $this->addedAt;
    }

    public function setAddedAt(?\DateTimeImmutable $addedAt): self
    {
        $this->addedAt = $addedAt;

        return $this;
    }

    /**
     * @return Collection|NewsCategories[]
     */
    public function getNewsCategories(): Collection
    {
        return $this->newsCategories;
    }

    public function addNewsCategory(NewsCategories $newsCategory): self
    {
        if (!$this->newsCategories->contains($newsCategory)) {
            $this->newsCategories[] = $newsCategory;
        }

        return $this;
    }

    public function removeNewsCategory(NewsCategories $newsCategory): self
    {
        $this->newsCategories->removeElement($newsCategory);

        return $this;
    }

    public function getNotation(): ?string
    {
        return $this->notation;
    }

    public function setNotation(?string $notation): self
    {
        $this->notation = $notation;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Connector\TournamentAssistantApi;
use App\Entity\News;
use App\Entity\Pages;
use App\Entity\Users;
use App\Form\CookieFormType;
use App\Service\Cookie;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends BaseController
{

    /**
     * @Route("/na", name="na")
     */
    public function index(Request $request): Response
    {
        return $this->render('default/utilities/na.html.twig', [
            'page' => null,
            'newsContentLength' => 164,
            'newsTitleLength' => 54,
        ]);
    }
    /**
     * @Route("/", name="homepage")
     */
    public function homepage(Request $request): Response
    {
        if (!$this->isGranted("ROLE_ADMIN")) {
            $this->redirectToRoute("na");
        }
        if(!$page = $this->em->getRepository(Pages::class)->findOneBy(['name' => 'homepage'])) {
            throw $this->createNotFoundException();
        }

        $topNews = $this->em->getRepository(News::class)->findVisible(1, 0);
        $news = $this->em->getRepository(News::class)->findVisible(2, 1);

        return $this->render('default/index.html.twig', [
            'page' => $page,
            'topNews' => $topNews,
            'newsArray' => $news,
            'newsContentLength' => 164,
            'newsTitleLength' => 54,
        ]);
    }

    /**
     * @Route("/_clear-cache", name="cacheClear")
     */
    public function clearCache(Request $request)
    {
        $response = new Response();
        $cache = new FilesystemAdapter();
        $output = $cache->clear();

        $response->setStatusCode(Response::HTTP_OK);
        $response->headers->set('Content-Type', 'text/plain');
        $response->setContent($output);

        return $response;
    }

    /**
     * @Route("/instagram-token", name="instagramToken")
     */
    public function instagramTokenAction(Request $request)
    {
        $response = new Response();
        // This prevents from accessing route directrly from browser because this token is sensitive
        if ($request->isXmlHttpRequest()) {
            return $response->setContent("IGQVJXQWZAiRHExeTRtZAU5oUDV5T0x3VHBYZAjUxSDB0cEpCNUN5bHc2WVE0NGo2akFFbFhKZA1FnelJ2U2xNQWJOSm5NcmtkdEJWRGRMVDVSQ21XODNLTGUxU2Vyd3JJbXIzcVF4R3R1NHpGeUowQmVvWgZDZD");
        }

        throw $this->createNotFoundException();
    }
}

src/Controller/GalleryController.php
<?php

namespace App\Controller;

use App\Entity\GalleryCategories;
use App\Entity\GalleryImages;
use App\Entity\Pages;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class GalleryController extends BaseController
{
    /**
     * @Route("/galerie", name="gallery")
     */
    public function index(Request $request): Response
    {
        if(!$page = $this->em->getRepository(Pages::class)->findOneBy(['name' => 'gallery'])) {
            throw $this->createNotFoundException();
        }

        $gallery = $this->em->getRepository(GalleryImages::class)->findVisible();
        $categories = $this->em->getRepository(GalleryCategories::class)->findVisible();

        return $this->render('default/gallery/gallery.html.twig', [
            'page' => $page,
            'gallery' => $gallery,
            'categories' => $categories,
        ]);
    }

    /**
     * @Route("/galerie/{slug}", name="gallery_detail")
     */
    public function galleryDetail(GalleryCategories $galleryCategory, Request $request)
    {
        if(!$page = $this->em->getRepository(Pages::class)->findOneBy(['name' => 'gallery'])) {
            throw $this->createNotFoundException();
        }
        $images = $galleryCategory->getGalleryImages();
        if (!empty($galleryCategory->getTitle())) {$page->setTitle($galleryCategory->getTitle());}
        if (!empty($galleryCategory->getMetaDescription())) {$page->setMetaDescription($galleryCategory->getMetaDescription());}
        if (!empty($galleryCategory->getKeywords())) {$page->setKeywords($galleryCategory->getKeywords());}
        if (!empty($galleryCategory->getHeading())) {$page->setHeading($galleryCategory->getHeading());}

        return $this->render('default/gallery/gallery_detail.html.twig', [
            'page' => $page,
            'gallery' => $galleryCategory,
            'images' => $images,
        ]);
    }
}

templates/default/gallery/gallery.html.twig
{% extends 'base.html.twig' %}

{% block title %}Czechsaber | {{ page.title|raw }}{% endblock %}

{% block meta %}
    <meta name="keywords" content="{{ page.keywords|raw }}">
    <meta name="description" content="{{ page.metaDescription|raw }}">
{% endblock %}

{% block sidebar %}
    {% embed "default/utilities/sidebar.html.twig" %}
        {% block galerie %}
            <div class="button-border">
                <li class="nav-item active  ">
                    <a class="nav-link" href="{{ path('gallery') }}">
                        <i class="fas fa-photo-video"></i>
                        <p>Galerie</p>
                    </a>
                </li>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block navbar %}
    {% embed "default/utilities/navbar.html.twig" %}{% endembed %}
{% endblock %}

{% block body %}
    <div class="wrapper-box">
        <div class="section">
            {% for category in categories %}
                <div class="gallery-container">
                    <a href="{{ path('gallery_detail', { slug: category.slug }) }}" class="button-border" style="width: 100%;">
                        <h2 class="text-left gallery-title">{{ category.name }}<span class="text-right">Zobrazit celou galerii</span></h2>
                    </a>
                    <div class="fg-gallery additional-class cols-4">
                        {% set missingSmallImages = 4 %}
                        {% set skippedImages = 0 %}
                        {% for key, image in category.galleryImages %}
                            {% if image.view == 1 and missingSmallImages != 0 %}
                                <img src="{{ asset(image.imgPath(image.imgName)) }}" alt="{{ image.alt }}">
                                {% set missingSmallImages = missingSmallImages-1 %}
                            {% else %}
                                {% if missingSmallImages != 0 %}
                                    {% set skippedImages = skippedImages+1 %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {% if missingSmallImages > 0 %}
                            {% for i in 0..missingSmallImages-1 %}
                                <img src="{{ asset('build/images/utilities/pripravujeme-dark.png') }}" alt="Zástupný obrázek CzechSaber">
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="fg-gallery ns cols-3">
                        {% set missingBigImages = 3 %}
                        {% for key, image in category.galleryImages|slice(4+skippedImages,3) %}
                            {% if image.view == 1 and missingBigImages != 0 %}
                                <img src="{{ asset(image.imgPath(image.imgName)) }}" alt="{{ image.alt }}">
                                {% set missingBigImages = missingBigImages-1 %}
                            {% endif %}
                        {% endfor %}
                        {% if missingBigImages > 0 %}
                            {% for i in 0..missingBigImages-1 %}
                                <img src="{{ asset('build/images/utilities/pripravujeme-dark.png') }}" alt="Zástupný obrázek CzechSaber">
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <button disabled class="c-btn" id="butt-for-gallery">
        <svg width="280px" height="120px" viewBox="0 0 180 60"><polyline points="179,1 179,59 1,59 1,1 179,1" class="bg-line" /><polyline points="179,1 179,59 1,59 1,1 179,1" class="hl-line" /></svg>
        <h2>{{ translator.getValue('SHOW_BUTTON', 'Zobrazit')|raw }}</h2>
    </button>

    <script>
        var a = new FgGallery('.fg-gallery', {
            cols: 4,
            style: {
                border: 'none',
                height: '220px',
                boxShadow: '0 2px 10px -5px #858585',
            }
        });

        var a = new FgGallery('.ns', {
            cols: 3,
            style: {
                border: '0 solid #fff',
                height: '280px',
            }
        });
    </script>

{% endblock %}

templates/default/gallery/gallery_detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Czechsaber | {{ page.title|raw }}{% endblock %}

{% block meta %}
	<meta name="keywords" content="{{ page.keywords|raw }}">
	<meta name="description" content="{{ page.metaDescription|raw }}">
{% endblock %}

{% block sidebar %}
	{% embed "default/utilities/sidebar.html.twig" %}
		{% block galerie %}
			<div class="button-border">
				<li class="nav-item active  ">
					<a class="nav-link" href="{{ path('gallery') }}">
						<i class="fas fa-book-open"></i>
						<p>Galerie</p>
					</a>
				</li>
			</div>
		{% endblock %}
	{% endembed %}
{% endblock %}

{% block navbar %}
	{% embed "default/utilities/navbar.html.twig" %}{% endembed %}
{% endblock %}

{% block header %}
	{% embed 'default/utilities/shared/_topfoto.html.twig' %}
		{% block topfoto %}
			<h2 class="top-foto-title">
				{{ gallery.name }}
			</h2>
		{% endblock %}
	{% endembed %}
{% endblock %}


{% block body %}

	<div class="wrapper-box">
		<div class="section">
			<div class="gallery-container">
				<a href="{{ path('gallery') }}" class="button-border" style="width: 100%;">
					<h2 class="text-left gallery-title">Zpět do galerie</h2>
				</a>
				<div class="fg-gallery additional-class cols-4">
					{% set missingSmallImages = 8 %}
					{% for key, image in gallery.galleryImages %}
						{% if image.view == 1 %}
							<img src="{{ asset(image.imgPath(image.imgName)) }}" alt="{{ image.alt }}">
							{% set missingSmallImages = missingSmallImages-1 %}
						{% endif %}
					{% endfor %}
					{% if missingSmallImages > 0 %}
						{% for i in 0..missingSmallImages-1 %}
							<img src="{{ asset('build/images/utilities/pripravujeme-dark.png') }}" alt="Zástupný obrázek CzechSaber">
						{% endfor %}
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	<button disabled class="c-btn" id="butt-for-gallery">
		<svg width="280px" height="120px" viewBox="0 0 180 60"><polyline points="179,1 179,59 1,59 1,1 179,1" class="bg-line" /><polyline points="179,1 179,59 1,59 1,1 179,1" class="hl-line" /></svg>
		<h2>{{ translator.getValue('SHOW_BUTTON', 'Zobrazit')|raw }}</h2>
	</button>

	<script>
      var a = new FgGallery('.fg-gallery', {
          cols: 4,
          style: {
              border: 'none',
              height: '260px',
              boxShadow: '0 2px 10px -5px #858585',
          }
      });

      var a = new FgGallery('.ns', {
          cols: 3,
          style: {
              border: '0 solid #fff',
              height: '320px',
          }
      });
	</script>

{% endblock %}